### ISSUE TITLE
We need to be able to add simulation results to the sciunit results cache

### ISSUE THREAD

**Issue by gidili** [MetaCell/geppetto-scidash#142]

**Comment by rgerkin** [comment]
You can see how the cache normally works [here](https://github.com/scidash/neuronunit/blob/dev/neuronunit/unit_test/cache_use.ipynb) and I have created a new notebook demonstrating how you might write directly to it [here](https://github.com/scidash/neuronunit/blob/dev/neuronunit/unit_test/cache_edit.ipynb).  The only thing that could cause problems is that because the lookup in the cache is by key, and the usual key is the model hash, any change to the model will cause it to run again instead of using the cached value.  So I should probably add either a dry run that gets the model set up exactly before you write to the cache, or the ability to have a test ask for a specific entry in the cache instead of just trying to find the key for the current model state.

**Comment by gidili** [comment]
Request: can we do the backend initialization on model instantiation so that the hash does not change immediately prior to the simulation run.

**Comment by gidili** [comment]
Thanks @rgerkin! 👍
