### ISSUE TITLE
Observation schema needs to explicitly specify units for each test

### ISSUE THREAD

**Issue by gidili** [MetaCell/geppetto-scidash#231]

**Comment by rgerkin** [comment]
The test classes themselves already have units (as python quantity types) in their `units` attribute.  So you should just check that attribute of the test's class and it should give you what you need.  Since it is a python quantity, you can access it's `name` or `symbol` attributes for the info you might want to show.  So, for example, `RheobaseTest.units.name` should be 'millivolt' and `RheobaseTest.units.symbol` should be "mV".  I may have forgotten units on some tests, so let me know if that comes up.  I should have a unit test for unit checking!
