### ISSUE TITLE
Implement model registration will work with links from neuroml-db

### ISSUE THREAD

**Issue by gidili** [MetaCell/geppetto-scidash#237]

**Comment by rgerkin** [comment]
@justasb The model registration page of the SciDash portal has a field where the user puts a URL.  SciDash then downloads this and begins setting up a model to be tested.  It is OK if this URL is only to a single neuroml or LEMS file, as long as the links to other required nml files can be parsed from it (e.g. if they are in include tags).  Is there a way to generate a URL that will get the main nml file (that is either the only nml file, or which has the includes tags needed to get the others), given a NeuroML-DB model ID?  On the website I see how to download a zip file, but presumably they are stored unzipped on the server so there is some way to access them that way.

**Comment by JustasB** [comment]
There are a couple of options:

1. In the [web model view,](https://neuroml-db.org/model_info?model_id=NMLCL000001) you can get the raw NML from the links in the files table:

![image](https://user-images.githubusercontent.com/10732358/56618521-b5900780-65d7-11e9-9bbd-adf7b99b2c93.png)

2. If you don't want to parse the web table, you can get the list of child models via the API: e.g.: https://neuroml-db.org/api/model?id=NMLCL001129

The "children" property tells you if there are any child models (if not, the model is a leaf model and will work on its own)

![image](https://user-images.githubusercontent.com/10732358/56618660-246d6080-65d8-11e9-8a1a-095eeac0ac5e.png)

3. If you use the zip file links in the web model view you mentioned, the zip file includes all the child dependencies of the model (e.g. you don't need to download anything else to make it work).

In addition, I would not rely just on a root NML model include tags, because they don't resolve a specific model in NMLDB it depends on. E.g. the include might require a "nax.channel.nml", but this is not specific, as there are few dozen "nax.channel.nml" files in the NMLDB. You would really either need to get the list of depencies from the web page, the API, or the ZIP file that includes them all.

**Comment by rgerkin** [comment]
@JustasB OK, let's try this out at the hackathon.

**Comment by rgerkin** [comment]
@gidili I think option #3 is the easiest.  

If someone puts a URL like if someone puts in the URL https://neuroml-db.org/model_info?model_id=NMLCL000129, which is the landing page for the NeuroML model with ID NMLCL000129, you should hit https://neuroml-db.org/GetModelZip?modelID=NMLCL000129&version=NeuroMLdownload on the backend, which will download a zip file, which when unzipped will contain the main nml file and all of its dependencies at the same level when unzipped.  In other words, it is everything you need to recursively parse and run the file using NeuroML tools we are already using.  

Is this OK?  I think you already doing something to the URLs entered in the bar, because some models in the production DB have URLs that are to GitHub landing pages, not to the raw nml files, so you must be rewriting them to "raw.githubusercontent.com" or something to download them.  I am just proposing that you rewrite to the zip file URL, and then unzip on your server.  

Using the direct GitHub link to the main .nml file won't be sufficient, because it's dependencies are stored elsewhere, not at the same level, so you would have to implement the same logic Justas already implemented when he figured out how to build the zip file.  So just use the zip file.  

One small concern is that this NeuroML-DB model may not be 100% stable, but really the only case where this could be a problem is that if a problem was identified in the model translation, since any other change to the model would result in a new model with a new NeuroML-DB ID.  I am happy to consider NeuroML-DB models 100% stable.

**Comment by gidili** [comment]
@rgerkin sounds good - let me get back to you with estimates for this as we are finishing everything else but should be doable.

We are using raw.githubusercontent urls in the model url field, forgot to say that (but we can put in place the substitution too).

**Comment by rgerkin** [comment]
OK, this should be enough to download the zip file, given the original NeuroML-DB landing page URL.  You could run this if 'neuroml-db.org' is found in the URL, for example, replacing `example_url` below with the URL given by the user:

```  
import os
from urllib import request, parse

# Example URL including an extra meaningless query key-value pair
example_url = 'https://neuroml-db.org/model_info?model_id=NMLCL000129&stuff=3'

# Parse the model_id from URL
parsed = parse.urlparse(example_url)
query = parse.parse_qs(parsed.query)
model_id = query['model_id'][0]

# Build the URL to the zip file and download it
zip_url = "https://neuroml-db.org/GetModelZip?modelID=%s&version=NeuroML" % model_id
location = '/tmp/%s.zip' % model_id
request.urlretrieve(zip_url, location)
assert os.path.isfile(location)
```

**Comment by gidili** [comment]
@rgerkin thanks for the snippet 👍 of course we would not be storing these files once it runs as we've made the decision together not to host models. We can always change this in the future if we realised it's convenient to keep a snapshot at that point in time.
