### ISSUE TITLE
Review django models (via diagram)

### ISSUE THREAD

**Issue by gidili** [MetaCell/geppetto-scidash#25]

**Comment by gidili** [comment]
Snapshot diagram of latest version of models [can be found here](https://github.com/MetaCell/scidash/blob/development/scidash_models.png) - this gets re-generated manually every time we change the models.

**Comment by rgerkin** [comment]
- If I recall correctly, in these diagrams at least some of the edges can represent intermediate tables not explicitly shown in the diagram, that just exist for the purpose of storing many-to-one and many-to-many relationships, is that correct?  

- The `unpicklable` attribute may or may not be necessary in this project.  It lists other attributes of the instance which cannot be pickled (even by powerful deep pickling implementations like cloudpickle), for example, a `neuron.h` variable.  However, I'm not sure that you will be doing any pickling here, as that is something that would already be done by the time the serialized object is sent to the server.  The `unpicklable` attribute is not used for unpickling or other deserialization, since missing attributes are just ignored.  

- I may be missing something about the table relationships (see my first comment) but, it looks like a test suite is an attribute of a test instance here rather than the other way around.  A test instance may be in one or more test suites, and a test suite may have one or more test instances.  The correct relationship is many-to-many, and I'm not sure that is reflected here.  I think that this diagram is showing that a model can have one or more capabilities, which is correct.

**Comment by gidili** [comment]
@rgerkin to your points: 

- The arrows represent a relationship of aggregation - so you can see that for any two entities that are connected the entity with the black dot endpoint "contains" the other and this is practically speaking implemented by having a foreign key to the contained entity id on the parent entity (also shown in the diagram as a foreign key attribute). There are no hidden tables so to speak, every entity on that diagram maps to a table on the db.   
- Agreed that the `unpickable` attribute is not needed, good catch -  I think we can safely remove!
- I think we missed that one test instance could be part of multiple test suites, I thought a given test instances could only belong to one test suite. We need to fix this.
