### ISSUE TITLE
More Test classes + Model classes (and working models) needed for testing

### ISSUE THREAD

**Issue by gidili** [MetaCell/geppetto-scidash#274]
Right now we have:
 
- ReducedModel + https://raw.githubusercontent.com/scidash/neuronunit/dash/neuronunit/models/NeuroML2/Izh2007One.net.nml
- RheobaseTest

We need some more coverage. 

Simulation was tested with random stuff on OSB and what works there works for us too but we need more sciunit compatible models with matching classes in neuronunit.

**Comment by rgerkin** [comment]
Try [this notebook](https://github.com/scidash/neuronunit/blob/dev/neuronunit/examples/model_zoo/models-1.ipynb).  It has a few examples, one model from OpenWorm against one test we haven't done yet, one model you've already used extensively but for a few different tests, and one model from the Allen Institute that doesn't work for me (because I don't currently have a way to programmatically extract the correct variables from NeuroML, but you do) but might work for you.  You will want to change the backend to your simulator instead of jNeuroML.  

I'd put more in, but I am having a hard time finding other examples that "just work" in jNeuroML (not even talking about testing, just simulating), and my NEURON backend is pretty limited too because it makes assumptions that are not true in many of the model found at OSB.

**Comment by rgerkin** [comment]
I ran this with the latest version of the dev branch for both sciunit and neuronunit.  For both repos, the dev branch now has everything from the dash branch plus a few more things.  I am not doing anything else on the dev branch right now that should affect you, so you can use it for now.

**Comment by gidili** [comment]
Results so far from @NeZanyat: 

- Izhinkevic works, results same
- ION channel - params not provided in test class @rgerkin 
- GLIF - fails in geppetto as well

**Comment by gidili** [comment]
@rgerkin also for the ion channel test we have noticed observations fields are arrays while in the UI we have it instrumented for one single figure for the examples we had seen so far. So I think we need to put some extra work to allow for this when we spot arrays there.

**Comment by rgerkin** [comment]
I added default params and params schema for ion channel tests.  We can deal with the other issue separately.
