### ISSUE TITLE
Test upload workflow

### ISSUE THREAD

**Issue by gidili** [MetaCell/geppetto-scidash#37]
Get at least 5 test models to test upload with real data coming from running sciunit/neuronunit tests

**Comment by rgerkin** [comment]
In [this notebook](https://github.com/scidash/neuronunit/blob/dev/docs/chapter3.ipynb) you can see an 8-test suite being constructed in cell 2.  The rheobase test is being added first (using data from the Allen Institute), and then seven other tests (using data from Neuroelectro.org), and hooks are being setup so that the latter 7 tests are run using stimulus parameters determined by the results of the first test (the rheobase test).  But those details don't really matter.  

Even though I set up a list of test classes (and params, all of which are None in this case), the money line is `tests += [cls(observation,params=params)]`, where I am adding to the list of tests a test instantiated from test class `cls` using observation `observation`, where that observation is obtained earlier using e.g. neuroelectro data.  But the observation is just a dictionary with certain requirements.  The `TestSuite` is then instantiated from that list of tests.  

API-breaking change I recently made to be aware of: `TestSuite` now takes the list of tests first as a positional argument, and then the name as a keyword argument, where as it used to be the other way around.  I did this to make it match `Model` and `Test`.
