### ISSUE TITLE
Upgrade scidash to latest version of geppetto client to take advantage of new functionality and smaller fixed footprint on first load

### ISSUE THREAD

**Issue by gidili** [MetaCell/geppetto-scidash#390]

**Comment by gidili** [comment]
This needs 1-2 hours to refine the estimate and break it down into smaller chunks

**Comment by ddelpiano** [comment]
Very high level areas to take into account:
- core, model and scidash simulator (backend) to test working.
- geppetto-scidash extension to use geppetto-client
- geppetto-scidash dependencies changed that might take time: react (moved to v16), material-ui, griddle used in geppetto-scidash > than the one used in geppetto-client.

**Comment by rgerkin** [comment]
When I think of "footprint on first load" I am thinking of geppetto-bundle.js.  Is that what you are talking about?  Doing everything in the cloud (and not on our servers that take 60 seconds to send data to parts of Europe!) should make this much less of a big deal, although for some users even the difference between 3 seconds and 2 seconds is a huge improvement in user experience.  

Are the latency and rate for getting this file from a Google Kubernetes cloud server no slower than what one would get from a CDN?  I'm still wondering if using a CDN for just this file could be worthwhile.

**Comment by ddelpiano** [comment]
> When I think of "footprint on first load" I am thinking of geppetto-bundle.js. Is that what you are talking about?

@rgerkin yes, with recent improvements of the geppetto code base we got this footprint reduced for other applications (e.g. Virtual Fly Brain) from 9Mb to ~1Mb, this will massively help.

> Are the latency and rate for getting this file from a Google Kubernetes cloud server no slower than what one would get from a CDN? I'm still wondering if using a CDN for just this file could be worthwhile.

I would recommend to start with moving scidash to the latest geppetto first since we need what this will require and it will massively help in terms of performance (as already mentioned) but also in term of stability, security and new feature that will be available in the future.
If this won't be good enough we could still allocate some time to investigate and estimate how long it will take to move static files to a CDN.

**Comment by gidili** [comment]
Even before we move to the latest Geppetto (as this may not be prioritised), as we transition to kubernetes cloud deployment we will already see big improvements compared to hosting under private networks (even on small EC2 instances if was already a lot better). If the result is not satisfactory (my guess is that it will be based on comparables on many other projects similarly hosted) and we decide not to upgrade to the latest geppetto at all we can always experiment the CDN option at that point.

**Comment by ddelpiano** [comment]
https://material-ui.com/guides/migration-v0x/ useful reference used for the material components.
