### ISSUE TITLE
Filters bugs

### ISSUE THREAD

**Issue by ddelpiano** [MetaCell/geppetto-scidash#481]
- hit DB only on enter keystroke.
- clean cached filters on logout.

**Comment by zsinnema** [comment]
I can't reproduce the filters not cleaned after logout.
Can someone try to write down how to reproduce it?

**Comment by rgerkin** [comment]
Go to site.  Login.  Test scores owner filter will be username.  Log out.  Test scores owner filter will be the same username, even though you are no logged out.  Expected behavior: the owner filter would reset to either: 
a) Whatever is the default for non-logged in user (presumably empty)
or
b) Whatever the user explicitly entered in that field, even potentially while logged in.  
but definitely not
c) Whatever was automatically set for the user by logging in

I think (a) makes the most sense.  The only case for (b) would be if we want to make all filters explicitly set by the user persist through login/logout.  I think it is probably easier to do (a).

**Comment by rgerkin** [comment]
FYI, this is on the http://35.188.223.116:8000/ version.

**Comment by zsinnema** [comment]
@rgerkin I've been able to reproduce and fix it :-)
