### ISSUE TITLE
Matching stored entities on upload from API

### ISSUE THREAD

**Issue by gidili** [MetaCell/geppetto-scidash#57]

**Comment by rgerkin** [comment]
Yes, for now I think if the URL matches it should be considered the same object, and we leave it to the (power) user to make the URL sufficiently detailed (e.g. include the commit hash) to ensure that changes to model/test class are reflected in the URL.  

As for instances themselves, another idea we haven't discussed, which would only apply within a single session (in the Python interpreter), would be to use the object's id, e.g. `id(var)` where `var` is some object in Python.  `id` is a built-in that maps to a location in memory.  It doesn't change when the object changes, but if both the object's hash and its id were the same, then the object would very likely be identical since it would not only have the same data but correspond to the same instance in memory.

**Comment by gidili** [comment]
Strategy recap:

- Model/test CLASSES --> match entities we already have on db with entities being uploaded based solely on class **URL** (if any)
- Everything else INSTANCES --> match entities we already have on db with entities being uploaded based on **ID of instance** (this will tell us if it's the actual same instance in a given upload session that is being uploaded again) + **hash**

**Comment by gidili** [comment]
Question for you on this @rgerkin: when serialising model/test classes we can see the url in the json but we don't see the attribute on any of the classes on the hierarchy. How do we set that url on the sciunit objects? Maybe if you can incorporate this into the [existing notebook example](https://github.com/scidash/neuronunit/blob/dev/neuronunit/unit_test/serialization_test.ipynb) would be helpful so we can test straight from your objects (right now we are working with serialized objects in order to sidestep this).

**Comment by rgerkin** [comment]
Added to dev branch in scidash/sciunit@3c79800a687f17553f9347af54b1431ccac6638f

**Comment by rgerkin** [comment]
Added a generic `url` attribute in scidash/sciunit@122bcc2b4b36a9fea56903876f5e4a09c6da84a8 which falls back to the git `remote_url` if it is left blank.
