### ISSUE TITLE
Alternate suites view not grouped by models

### ISSUE THREAD

**Issue by gidili** [MetaCell/geppetto-scidash#68]
At the moment suites view is grouped by model by design because this was the most useful representation to start with. This view has the limitation that the score matrix presented on score click for a given suite for a given model is mono-dimensional (all scores for tests on a given model).

It would be nice to have an alternate suites view that is not grouped by models, so that the score matrix that we present on score click is bi-dimensional.

Need to do a mockup of what this would like and how to transition from one view to the other.

**Comment by rgerkin** [comment]
@gidili @scrook 
There are a few different bi-dimensional views here that should be distinguished:
1) Suites vs Models
2) Tests vs Models
3) Tests in a given suite vs Models
I think these are all valuable in some form and ultimately I would like to see them all.  

The value of (1) is that it gives you a summary of relative model performance across multiple kinds of tests (grouped into different suites).  It is a high-level summary of relative model validity.  

The value of (2) is similar to (1), but with the granularity of individual test performance.  This one is probably the least necessary, but some tests "stand alone" and have not been put into suites, although maybe best practice would be to put even individual tests into suites (in Python) so that approach (1) would be sufficient for most cases.  

The value of (3) is to see how a model got the score it did on a given suite, i.e. on which tests within the suite it is strong and weak.  This is already possible now with the current version of the site.  When more models are added as rows it also allows the user to see a narrower version of (2), restricted to the tests within one suite.  

Last week I think we only talked about (3), and the current light box which shows Tests in a given suite vs one model is a starting point.  Possible ways to extend this include a) a button within that light box, b) Clicking the suite itself on the main view, or something else I haven't thought of.  

(1) and (2) seem as simple (to me) as rendering the main view, for each of suites (1) and tests (2) as a matrix instead of a table.  The same data would be there, except the colored cells would appear in a matrix, and the suite/test names would be grouped in rows and the model names would become columns.  I hate to say it, but really it should be the transpose of that (model names as rows and test/suite names as columns) because the number of model instances could be far greater than the number of test/suite instances, and the more numerous data looks better as rows for scrolling reasons.  

All of these options require rethinking how we filter model names so that we get a manageable set of them that we actually want to see.  We should also filter suite/test names, but I don't care about filtering test names within a suite (in (3)) because the user decides in the first place which tests to put into the suite.  Options for filtering (beyond the textbox) include checkboxes and other toggles.  I think maybe we are missing a high-level concept like a "Collection", where the user can add certain items of importance to a transient list, and then be able to display only things in that list.  They might add to the list in the normal views with a checkbox or by clicking something in the light box for that item.  And then they should be able to reset their collection as well.  I think having a collection will help make a lot of things easier going forward as well.

**Comment by gidili** [comment]
Thanks for putting this down @rgerkin - I am digesting and will get back with my thoughts about specific points. 

This is what I mean when I say that often times the only way to get to the ideal functionality is to interact with the software 😄it's easy to agree on a mockup but only by using it you get a better feel for what would be the most useful representation of the data.  

In general now that we have laid the foundation there's nothing stopping us from having all sorts of imaginable transposed views based on ideas we get from playing with the current version in terms of what would provide the most value. Even that doesn't mean we scrap what we have now, we can use the current iteration as a playground to keep adding useful ways to explore sciunit output side by side. 👍
